name: release

on:
  release:
    types: [created]

env:
  node_version: 16

jobs:

  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: discojs/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: discojs/package-lock.json
      - run: npm ci
      - run: npm run build
      # copy dependencies from discojs to discojs/discojs-node and discojs/discojs-web
      - run: npx ts-node publish.ts
      # publish @epfml/discojs
      - run: npm publish --access public
        working-directory: discojs/discojs-web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # publish @epfml/discojs-node
      - run: npm publish --access public
        working-directory: discojs/discojs-node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --access public
        working-directory: server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
