name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

env:
  node_version: 16

jobs:

  push-tag-and-npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: |
            discojs/package-lock.json
            server/package-lock.json

      - name: Build @epfml/discojs and @epfml/discojs-node
        run: |
          npm ci
          npm run build
        working-directory: discojs

      - name: Build @epfml/disco-server
        run: |
          npm ci
          npm link ../discojs/discojs-node
          npm run build
        working-directory: server

      - name: Bump the @epfml/discojs version
        run: npm version ${{ inputs.version }}
        working-directory: discojs/discojs-web

      - name: Bump the @epfml/discojs-node version
        run: npm version ${{ inputs.version }}
        working-directory: discojs/discojs-node

      - name: Bump the @epfml/disco-server version
        run: npm version ${{ inputs.version }}
        working-directory: server

      - name: Bump @epfml/disco-server dependency to @epfml/discojs-node
        run: npx ts-node publish.ts
        working-directory: server

      - name: Create version commit and tag
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'bot@users.noreply.github.com'
          git commit -am "v${{ inputs.version }}"
          git tag -a "v${{ inputs.version }}" -m "disco: v${{ inputs.version }}"
          git push
          git push --tags

      - name: Write dependencies for @epfml/discojs and @epfml/discojs-node
        run: npx ts-node publish.ts
        working-directory: discojs

      - name: Publish @epfml/discojs
        run: npm publish --access public
        working-directory: discojs/discojs-web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @epfml/discojs-node
        run: npm publish --access public
        working-directory: discojs/discojs-node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @epfml/disco-server
        run: npm publish --access public
        working-directory: server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
